
TYPE
	MachineState_type : 	STRUCT  (*State machine*)
		Sub0 : BOOL; (*Subroutine 0*)
		Sub1 : BOOL; (*Subroutine 1*)
		Sub2 : BOOL; (*Subroutine 2*)
		Sub3 : BOOL; (*Subroutine 3*)
		Sub4 : BOOL; (*Subroutine 4*)
		Sub5 : BOOL; (*Subroutine 5*)
		Sub6 : BOOL; (*Subroutine 6*)
		Sub7 : BOOL; (*Subroutine 7*)
		Sub8 : BOOL; (*Subroutine 8*)
		Sub9 : BOOL; (*Subroutine 9*)
	END_STRUCT;
	di_type : 	STRUCT  (*Digital inputs*)
		L1CarriageRight : BOOL; (*Carriage limit right*)
		L2CarriageLeft : BOOL; (*Carriage limit left*)
		L3BagLifterUpper : BOOL; (*Bag lifter limit upper*)
		L4BagLifterLower : BOOL; (*Bag lifter limit lower*)
		L5DuckBillLeft : BOOL; (*Duck bill limit left*)
		L6DuckBillRight : BOOL; (*Duck bill limit right*)
		L7GripperOpen : BOOL; (*Gripper open limit*)
		L8VacuumConfirm : BOOL; (*Vacuum confirmation*)
		L9SwingArmUpper : BOOL; (*Swing arm limit upper*)
		L10SwingArmLower : BOOL; (*Swing arm limit lower*)
		L11EmptyBagInboundConv : BOOL; (*Empty bag inbound conveyor*)
		L12Cyl7SpreaderSwitch : BOOL; (*Activate Cyl7 switch*)
		Bagger1Ready : BOOL; (*Ready signal from bagger*)
		Bagger2OnSpout : BOOL; (*No bag on spout from bagger*)
		ConveyorOn : BOOL; (*Conveyor on signal from robotic palletizer*)
		SafeToRun : BOOL; (*Safe to run signal from safety light curtain*)
		ChairDischarge : BOOL; (*Chair discharge signal*)
		SealerArmUp : BOOL; (*Sealer arm up signal*)
		ChairIn : BOOL; (*Chair in signal*)
	END_STRUCT;
	do_type : 	STRUCT  (*Digital outputs*)
		Cyl1CarriageLeft : BOOL; (*Move carriage left*)
		Cyl1CarriageRight : BOOL; (*Move carriage right*)
		Cyl2SwingArmUp : BOOL; (*Move swinging arm up*)
		Cyl2SwingArmDown : BOOL; (*Move swinging arm down*)
		Cyl3EmptyBagUp : BOOL; (*Lift empty bags up*)
		Cyl3DownToEmptyBag : BOOL; (*Move down to empty bags*)
		Cyl4DuckBillLeft : BOOL; (*Move duck bill assembly left*)
		Cyl4DuckBillRight : BOOL; (*Move duck bill assembly right*)
		Cyl5DuckBillIn : BOOL; (*Move duck bill in*)
		Cyl5DuckBillOut : BOOL; (*Move duck bill out*)
		Cyl6DuckBillOpen : BOOL; (*Open duck bill*)
		Cyl6DuckBillClose : BOOL; (*Close duck bill*)
		Cyl7Spreader : BOOL; (*Bag valve spreader*)
		Cyl8DropOpen : BOOL; (*Drop bag*)
		Cyl8GripClose : BOOL; (*Grip bag*)
		Vac1 : BOOL; (*Attach bag to bag lifter*)
		Purge1 : BOOL; (*Purge vacuum lines*)
		Alarm : BOOL; (*Error present*)
		Running : BOOL; (*Machine running*)
	END_STRUCT;
	ModuleOK_type : 	STRUCT  (*Module statuses*)
		PowerSupply : BOOL; (*X20PS9600 status*)
		DigitalInput : BOOL; (*X20DI8371 status*)
		DigitalOutput : BOOL; (*X20DO9322 status*)
		DigitalInputa : BOOL; (*X20DI8371a status*)
		DigitalOutputa : BOOL; (*X20DO9322a status*)
		DigitalInputb : BOOL; (*X20DI8371b status*)
	END_STRUCT;
	Timer_type : 	STRUCT  (*System timers*)
		HomePos : TIME; (*Homing Position timer value*)
		BagOnSpout : TIME; (*Bag on Spout timer value*)
		VacuumConfirm : TIME; (*Vacuum Confirmation timer value*)
		Cyl5 : TIME; (*Cyl 5 timer value*)
		Cyl6 : TIME; (*Cyl 6 timer value*)
		Cyl7 : TIME; (*Cyl 7 timer value*)
		GripperRetract : TIME; (*Gripper retract timer value*)
		SwingArm : TIME; (*Swing arm timer value*)
	END_STRUCT;
	Machine_type : 	STRUCT  (*Machine structure type*)
		Cmd : MachineCmd_type; (*Machine commands*)
		Par : MachinePar_type; (*Machine parameters*)
		Sts : MachineSts_type; (*Machine statuses*)
	END_STRUCT;
	MachineCmd_type : 	STRUCT  (*Machine commands*)
		Home : BOOL; (*Home*)
		Initialize : BOOL; (*Initialize - start from home*)
		Start : BOOL; (*Start machine*)
		Stop : BOOL; (*Stop machine*)
		ErrorReset : BOOL; (*Reset error*)
		Wait : BOOL; (*Wait state*)
		Pause : BOOL; (*Pause machine*)
		Resume : BOOL; (*Resume subroutine*)
	END_STRUCT;
	MachinePar_type : 	STRUCT  (*Machine parameters*)
		VacuumFail : UDINT; (*Vacuum confirmation failure*)
		VacuumFailTotal : UDINT; (*Vacuum confirmation failure total*)
		Bagger2Fail : UDINT; (*Bagger 2 on Spout failure*)
		Bagger2FailTotal : UDINT; (*Bagger 2 on Spout failure total*)
	END_STRUCT;
	MachineSts_type : 	STRUCT  (*Machine statuses*)
		IsHomed : BOOL; (*Is homed*)
		Cyl6LimitClose : BOOL; (*Cyl 6 timer feedback - duck bill close*)
		Cyl6LimitOpen : BOOL; (*Cyl 6 timer feedback - duck bill open*)
		Cyl5LimitOut : BOOL; (*Cyl 5 timer feedback - duck bill out*)
		Cyl5LimitIn : BOOL; (*Cyl 5 timer feedback - duck bill in*)
		Error : BOOL; (*Error detected*)
		HomePosTimeout : BOOL; (*Home Position timeout*)
		VacuumTimeout : BOOL; (*Vacuum Confirmation timeout*)
		AttemptsLeft : BOOL; (*Attempts left before error - vacuum*)
		NoAttemptsLeft : BOOL; (*No vacuum attempts left - error*)
		Bagger2Timeout : BOOL; (*Bag on Spout timeout*)
		BaggerAttemptsLeft : BOOL; (*Attempts left before error - Bagger 2*)
		NoBaggerAttemptsLeft : BOOL; (*No Bagger 2 attempts left - error*)
	END_STRUCT;
	Input_type : 	STRUCT  (*Machine inputs*)
		L1CarriageRight : BOOL; (*Carriage limit right*)
		L2CarriageLeft : BOOL; (*Carriage limit left*)
		L3BagLifterUpper : BOOL; (*Bag lifter limit upper*)
		L4BagLifterLower : BOOL; (*Bag lifter limit lower*)
		L5DuckBillLeft : BOOL; (*Duck bill limit left*)
		L6DuckBillRight : BOOL; (*Duck bill limit right*)
		L7GripperOpen : BOOL; (*Gripper open limit*)
		L8VacuumConfirm : BOOL; (*Vacuum confirmation*)
		L9SwingArmUpper : BOOL; (*Swing arm limit upper*)
		L10SwingArmLower : BOOL; (*Swing arm limit lower*)
		L11EmptyBagInboundConv : BOOL; (*Empty bag inbound conveyor*)
		L12Cyl7SpreaderSwitch : BOOL; (*Activate Cyl7 switch*)
		Bagger1Ready : BOOL; (*Ready signal from bagger*)
		Bagger2OnSpout : BOOL; (*No bag on spout from bagger*)
		ConveyorOn : BOOL; (*Conveyor on signal from robotic palletizer*)
		SafeToRun : BOOL; (*Safe to run signal from safety light curtain*)
		ChairDischarge : BOOL; (*Chair discharge signal*)
		SealerArmUp : BOOL; (*Sealer arm up signal*)
		ChairIn : BOOL; (*Chair in signal*)
	END_STRUCT;
	Output_type : 	STRUCT  (*Machine outputs*)
		Cyl1CarriageLeft : BOOL; (*Move carriage left*)
		Cyl1CarriageRight : BOOL; (*Move carriage right*)
		Cyl2SwingArmUp : BOOL; (*Move swinging arm up*)
		Cyl2SwingArmDown : BOOL; (*Move swinging arm down*)
		Cyl3EmptyBagUp : BOOL; (*Lift empty bags up*)
		Cyl3DownToEmptyBag : BOOL; (*Move down to empty bags*)
		Cyl4DuckBillLeft : BOOL; (*Move duck bill assembly left*)
		Cyl4DuckBillRight : BOOL; (*Move duck bill assembly right*)
		Cyl5DuckBillIn : BOOL; (*Move duck bill in*)
		Cyl5DuckBillOut : BOOL; (*Move duck bill out*)
		Cyl6DuckBillOpen : BOOL; (*Open duck bill*)
		Cyl6DuckBillClose : BOOL; (*Close duck bill*)
		Cyl7Spreader : BOOL; (*Bag valve spreader*)
		Cyl8DropOpen : BOOL; (*Drop bag*)
		Cyl8GripClose : BOOL; (*Grip bag*)
		Vac1 : BOOL; (*Attach bag to bag lifter*)
		Purge1 : BOOL; (*Purge vacuum lines*)
		Alarm : BOOL; (*Error detected*)
		Running : BOOL; (*Machine Running*)
	END_STRUCT;
	ErrorID_enum : 
		( (*Error ID enumeration*)
		HOMING_TIMEOUT := 1, (*Homing position timeout*)
		SAFE_TO_RUN := 2, (*Machine not Safe to Run*)
		CONVEYOR := 3, (*Conveyor not on*)
		MODULE_OK := 4, (*Module OK status error*)
		VACUUM_FAILURE := 5, (*Vacuum failure (after 3 attempts)*)
		BAG_ON_SPOUT_FAILURE := 6 (*No Bag on spout (after 3 attempts)*)
		);
END_TYPE
