struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
_BUR_LOCAL struct TON TON_Cyl6;
_BUR_LOCAL struct TON TON_Cyl5;
_BUR_LOCAL struct TON TON_VacuumConfirm;
_BUR_LOCAL struct TON TON_BagOnSpout;
_BUR_LOCAL struct TON TON_HomePos;
_BUR_LOCAL struct TON TON_Cyl7Switch;
_BUR_LOCAL plctime Cyl7SwitchTimer;
_BUR_LOCAL struct TON TON_Cyl3;
_BUR_LOCAL plcbit ExecuteJump;
_BUR_LOCAL struct TON TON_Cyl5_Sub2;
_BUR_LOCAL struct TON TON_Cyl6_Sub2;
_BUR_LOCAL struct TON TON_Cyl5_Sub0;
_BUR_LOCAL struct TON TON_Cyl6_Sub0;
_BUR_LOCAL struct TON TON_Cyl5_Sub4;
_BUR_LOCAL struct TON TON_Cyl6_Sub4;
_BUR_LOCAL struct TON TON_Cyl6_Sub4_2;
_BUR_LOCAL struct TON TON_GripperRetract;
_BUR_LOCAL struct TON TON_SwingArm;
_BUR_LOCAL unsigned long StateOld;
_BUR_LOCAL plcbit StateOldIsSet;
